spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret: 
          google:
            client-id: 
            client-secret: 
# ...